blank_issues_enabled: true
contact_links:
  - name: 💬 Not sure? Open a blank issue
    url: https://github.com/issues/new
    about: If your issue doesn't fit the templates above, feel free to open a blank one.
